// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HandleEventResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleEventResponse) Reset()         { *m = HandleEventResponse{} }
func (m *HandleEventResponse) String() string { return proto.CompactTextString(m) }
func (*HandleEventResponse) ProtoMessage()    {}
func (*HandleEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *HandleEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleEventResponse.Unmarshal(m, b)
}
func (m *HandleEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleEventResponse.Marshal(b, m, deterministic)
}
func (m *HandleEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleEventResponse.Merge(m, src)
}
func (m *HandleEventResponse) XXX_Size() int {
	return xxx_messageInfo_HandleEventResponse.Size(m)
}
func (m *HandleEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleEventResponse proto.InternalMessageInfo

func (m *HandleEventResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*HandleEventResponse)(nil), "pb.HandleEventResponse")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe7, 0x62, 0x75,
	0x05, 0x09, 0x09, 0x89, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xe4, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x41, 0x38, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12,
	0x4c, 0x60, 0x71, 0x18, 0x57, 0x49, 0x9f, 0x4b, 0xd8, 0x23, 0x31, 0x2f, 0x25, 0x27, 0x15, 0xac,
	0x3d, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x18, 0x45, 0x03, 0x23, 0x8a, 0x06, 0x23, 0x47, 0x2e,
	0x1e, 0xb0, 0xd2, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x43, 0x2e, 0xee, 0x0c, 0x84,
	0x01, 0x42, 0x9c, 0x7a, 0x05, 0x49, 0x7a, 0x60, 0xa6, 0x94, 0x38, 0x88, 0x89, 0xc5, 0x70, 0x27,
	0xb6, 0x28, 0x16, 0x3d, 0xfd, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0xfb, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x0a, 0xf0, 0x6e, 0x5f, 0xce, 0x00, 0x00, 0x00,
}
