// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EventResultStream struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResultStream) Reset()         { *m = EventResultStream{} }
func (m *EventResultStream) String() string { return proto.CompactTextString(m) }
func (*EventResultStream) ProtoMessage()    {}
func (*EventResultStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventResultStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResultStream.Unmarshal(m, b)
}
func (m *EventResultStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResultStream.Marshal(b, m, deterministic)
}
func (m *EventResultStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResultStream.Merge(m, src)
}
func (m *EventResultStream) XXX_Size() int {
	return xxx_messageInfo_EventResultStream.Size(m)
}
func (m *EventResultStream) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResultStream.DiscardUnknown(m)
}

var xxx_messageInfo_EventResultStream proto.InternalMessageInfo

func (m *EventResultStream) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EventResultStream) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type HandleEventResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleEventResponse) Reset()         { *m = HandleEventResponse{} }
func (m *HandleEventResponse) String() string { return proto.CompactTextString(m) }
func (*HandleEventResponse) ProtoMessage()    {}
func (*HandleEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *HandleEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleEventResponse.Unmarshal(m, b)
}
func (m *HandleEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleEventResponse.Marshal(b, m, deterministic)
}
func (m *HandleEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleEventResponse.Merge(m, src)
}
func (m *HandleEventResponse) XXX_Size() int {
	return xxx_messageInfo_HandleEventResponse.Size(m)
}
func (m *HandleEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleEventResponse proto.InternalMessageInfo

func (m *HandleEventResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Events struct {
	Event                []*Event `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*EventResultStream)(nil), "pb.EventResultStream")
	proto.RegisterType((*HandleEventResponse)(nil), "pb.HandleEventResponse")
	proto.RegisterType((*Events)(nil), "pb.Events")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x42, 0x82, 0x7a, 0xe9, 0xc2, 0x81, 0x20, 0x62, 0xa1, 0xca, 0x42, 0x18, 0x08,
	0xa5, 0x0c, 0x0c, 0x6c, 0x01, 0x24, 0x06, 0xa6, 0x76, 0x63, 0x73, 0x9a, 0x13, 0xb2, 0xe4, 0x26,
	0x56, 0x7c, 0xed, 0x4b, 0xf3, 0x12, 0x28, 0x76, 0x03, 0x91, 0x68, 0xa4, 0x6e, 0x77, 0xbf, 0xf2,
	0x7d, 0xf7, 0x2b, 0x86, 0x88, 0xb6, 0x54, 0x71, 0x66, 0x9a, 0x9a, 0x6b, 0x1c, 0x99, 0x22, 0x79,
	0x82, 0xe0, 0xad, 0x8d, 0xf0, 0x1c, 0x02, 0x56, 0xac, 0x29, 0x16, 0x53, 0x91, 0x8e, 0x17, 0x7e,
	0xc1, 0x18, 0x4e, 0xd6, 0x64, 0xad, 0xfc, 0xa2, 0x78, 0xe4, 0xf2, 0x6e, 0x4d, 0x3e, 0xe0, 0xd4,
	0x81, 0x0b, 0xb2, 0x1b, 0xcd, 0x4b, 0x6e, 0x48, 0xae, 0xf1, 0x02, 0x42, 0xcb, 0x92, 0x37, 0x76,
	0x67, 0xd9, 0x6d, 0x78, 0x0d, 0x81, 0x3b, 0xec, 0x24, 0xd1, 0x7c, 0x9c, 0x99, 0x22, 0xf3, 0xb4,
	0xcf, 0x93, 0x3b, 0x38, 0x7b, 0x97, 0x55, 0xa9, 0xa9, 0x73, 0x9a, 0xba, 0xb2, 0x34, 0xe4, 0x4b,
	0x6e, 0x21, 0x74, 0x1f, 0xf6, 0xcc, 0x62, 0x7a, 0xb4, 0xcf, 0x3c, 0xff, 0x16, 0x30, 0x71, 0xc1,
	0x92, 0x9a, 0xad, 0x5a, 0x11, 0x3e, 0x40, 0xd4, 0x3b, 0x85, 0x7f, 0xc4, 0xd5, 0x65, 0x3b, 0xee,
	0xab, 0xf1, 0xdc, 0xb5, 0x7b, 0x25, 0x96, 0x4a, 0x53, 0x79, 0x30, 0x3a, 0x13, 0x78, 0x03, 0x93,
	0x17, 0xad, 0xda, 0x02, 0xfe, 0x1f, 0xf5, 0x28, 0xf8, 0x1d, 0x6d, 0x2a, 0x30, 0x87, 0x38, 0x57,
	0xa5, 0x6a, 0x68, 0xc5, 0xaa, 0xae, 0xa4, 0xf6, 0xad, 0xff, 0x41, 0x43, 0xa7, 0x52, 0x31, 0x13,
	0x79, 0xf8, 0x79, 0x9c, 0xdd, 0x9b, 0xa2, 0x08, 0xdd, 0x0b, 0x3f, 0xfe, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x48, 0x10, 0x10, 0x7e, 0xf0, 0x01, 0x00, 0x00,
}
